cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

scala:
   - 2.11.12
   - 2.12.6

script:
  - sbt "++${TRAVIS_SCALA_VERSION}! -v" test

jdk:
  - oraclejdk8
  - openjdk10

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
