cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

scala:
   - 2.11.12
   - 2.12.6

script:
  - sbt "++${TRAVIS_SCALA_VERSION}! -v" test

jdk:
  - oraclejdk8

matrix:
  include:
  - jdk: openjdk10
    scala: 2.12.6
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
